/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "== Statistics ==": "== 统计 ==",
    "": "",
    "Main Menu": "主菜单",
    "Give Up": "放弃",
    "Final Score": "最终分数",
    "Hebei": "河北",
    "in the corner.": "在角落里。",
    "How to play this game, introduce some game mechanics, and how to get a higher score in this game.": "如何玩这个游戏，介绍一些游戏机制，以及如何在这个游戏中获得更高的成绩。",
    "Evolution": "演变",
    "evolution": "演变",
    "Intelligence talent:": "智力天赋：",
    "evolution chance": "演变几率",
    "Extreme Mode": "极限模式",
    "Graduation": "毕业",
    "Graduation Requirement": "毕业要求",
    "Graduate now!": "现在毕业！",
    "Grid": "网格",
    "Introduction": "介绍",
    "Merge": "合并",
    "Mode to unlock.": "模式来解锁。",
    "Score & Rank": "分数 & 排名",
    "When a": "当一个",
    "You gain:": "你获得了:",
    "Zhongkao Tree": "中考树",
    "You gains some": "你获得了一些",
    "Your total talent after your progression to high school:": "升入高中后您的总天赋：",
    "Welcome to my new game: Hebei Zhongkao Tree!(currently version: Irritated SFGirls, Realised in August 25th, 2023).": "欢迎来到我的新游戏：河北中考树！（当前版本：Irritated SFGirls，2023年8月25日实现）。",
    "The game is only published in g8hh.com and galaxy.": "该游戏仅在 g8hh.com、gityx.com 和 galaxy 上发布。",
    "Stemina": "耐力",
    "stemina": "耐力",
    "Stamina": "耐力",
    "Scholarship Upgrades": "奖学金升级",
    "scholarship upgrades": "奖学金升级",
    "Scholarships": "奖学金",
    "scholarships": "奖学金",
    "Some general info for this game.": "该游戏的一些常规信息。",
    "Some info for how scholarship and upgrades works.": "有关奖学金和升级如何运作的一些信息。",
    "Ssh...this part is a secret. All formulas will be appear there in next version.": "嘘……这部分是秘密。 所有公式将在下一版本中出现。",
    "Some upgrades are rebuyable and others are not. Each upgrade produces a eternal boost for the game.": "有些升级是可重复购买的，有些则不然。 每次升级都会为游戏带来永恒的提升。",
    "Level:": "等级:",
    "Manage talent:": "管理天赋：",
    "Graduate for one time to": "毕业一次以",
    "Balance": "平衡",
    "Back": "返回",
    "block generation": "方块生成",
    "Best Score:": "最好分数：",
    "But there are only 4 in the current version": "但目前版本只有4个",
    "Causal Mode": "因果模式",
    "Cost:": "成本:",
    "Close": "关闭",
    "Equipments": "装备",
    "Emotional talent:": "情感天赋：",
    "Chapter 1: General Info": "第 1 章：常规信息",
    "Chapter 2: How to Play": "第 2 章：玩法",
    "Chapter 3: Scholarship && Upgrades": "第 3 章：奖学金和升级",
    "== Tech Slots ==": "== 科技槽 ==",
    "1-1 General": "1-1 常规",
    "2-1 Getting Started": "2-1 入门",
    "2-2 Basic Gameplay": "2-2 基本玩法",
    "2-3 High-Score Guide": "2-3 高分指南",
    "2-4 Game Formula": "2-4 游戏公式",
    "2. Highest value block in grid": "2. 网格中值最高的方块",
    "3-1 Scholarship": "3-1奖学金",
    "3-2 Scholarship Upgrades": "3-2 奖学金升级",
    "3. Reach a rank of top 400": "3. 达到前400名的排名",
    "Notebook Block": "笔记本方块",
    "Notebook block": "笔记本方块",
    "notebook block": "笔记本方块",
    "notebook blocks": "笔记本方块",
    "and": "和",
    "Gameplay factor": "游戏玩法因子",
    "gameplay factor": "游戏玩法因子",
    "happened, each": "发生了，每个",
    "is in the grid. The way to eliminate": "在网格中。 消除方法",
    "Reset": "重置",
    "This game is still in beta version, so it has not been adapted to mobile devices yet. Mobile players, please wait for the next game version to be released. We are very sorry. Please use computer or iPad to play this game.": "该游戏目前仍处于测试版，因此尚未适配移动设备。 手机玩家请等待下一个游戏版本的发布。 我们很抱歉。 请使用电脑或iPad来玩这个游戏。",
    "This game contains 3 different difficuties:": "该游戏包含 3 个不同的难度：",
    "There are 16 upgrades(4 rows, 4 columns) in the shop. When you buy a upgrade, the upgrade above it must be puchased.": "商店中有16个升级（4行，4列）。 当您购买升级时，必须先购买其之上的升级。",
    "The game will be updated every 2-3 weeks.": "游戏每 2-3 周更新一次。",
    "The current tile can jump to the nearest open space or same number tile in each of the four cardinal directions. Any smaller negative blocks jumped this way\n                            will be removed. if you don't jump, then a new tile is generated where you left.": "当前方块可以跳转到最近的空地或四个基本方向中每个方向上相同数量的方块。 以此方式跳跃的任何较小的负块将被删除。 如果你不跳，那么会在你离开的地方生成一个新的方块。",
    "unlock.": "解锁.",
    "unlocked first, higher difficuties requires you to reach a certain rank in": "先解锁，更高的难度需要你达到一定的排名在",
    "When it is below 1%, you'll lose the game.": "当它低于1%时，你就会输掉游戏。",
    "When you need to move a corner block, you'd better merge it with the blocks which are in the same row or in the same column. Because this way could avoid generating a": "当您需要移动角落的方块时，最好将其与同一行或同一列的方块合并。 因为这种方式可以避免生成",
    "will be unlocked.": "将会被解锁。",
    "will have a large probability to generate a": "将有很大的概率产生一个",
    "will have a small probability to generate a": "将有很小的概率产生一个",
    "Try to buy upgrades and get better rank next time!": "尝试购买升级并下次获得更好的排名！",
    "will be created as well.(2->4->8->16, etc.)": "也会被创建。（2->4->8->16，等等）",
    "will be happened at the 31st turn and every 10 turns after that. (without any boost) When a": "将在第 31 回合发生，此后每 10 回合发生一次。 （没有任何提升）当",
    "with a same value merged, you'il gain some score and some": "合并相同的值，你会获得一些分数和一些",
    "There is a 5x5-grid in the main\n                            game. Every unit of grid can contain a": "主游戏中有一个 5x5 网格。 每个网格单元可以包含一个",
    ". A higher difficuty means harder to reach a high rank in game,\n                            but increase coin gain and the quality of the graduted-students.": "。 较高的难度意味着在游戏中达到较高排名的难度较大，但会增加金币收益和毕业的质量。",
    ". Grid resets when\n                            you starts a new game.": "。 当您开始新游戏时，网格会重置。\n",
    ", a\n                            higher-value": ",一个\n 更高的值",
    ". You will lose score and": "。 你会失去分数并且",
    "(Can't Merge)": "（不能合并）",
    "(Can Merge)": "（可合并）",
    "(Can Move to here)": "（可以移到这里）",
    "(Can't Move to here)": "（不能移到这里）",
    "(Main Block)": "（主方块）",
    "(start at 20). The": "（从 20 开始）。",
    "(Township general middle school)": "（乡镇普通中学）",
    "(When blue and red merged, it *can't* be eliminated)": "（当蓝色和红色合并时，它*无法*被消除）",
    "(When blue and red merged, it can be eliminated)": "（蓝色和红色融合后即可消除）",
    "[Beta Version]": "[Beta 版本]",
    "1st Term": "第一学期",
    "1. Not in any versus challenge": "1. 不参加任何对抗挑战",
    "after a gameplay. The amount is based on your\n                            game score, step ranks and": "玩完游戏后。 金额取决于您的\n游戏得分、步数排名和",
    "After you earns a copper coin, the": "当你赚到铜币后，",
    "Always try to do jump-merging instead of normal-merging in game to get higher score.": "在游戏中始终尝试进行跳跃合并而不是正常合并以获得更高的分数。",
    "appeared, eliminate\n                            it as fast as you can.": "出现了，请尽快消灭它。",
    "are available in different currencies, including iron, copper,\n                            silver, etc. The two adjacent currencies are decimal 100, but in the advanced currencies, it is decimal 1000, decimal 10000 or even higher.": "有不同的货币，包括铁、铜、银等。相邻的两种货币都是十进制的100，但在高级货币中，是十进制的1000、十进制的10000甚至更高。",
    "button in the main tab to start the game.": "按钮在主选项卡中以开始游戏。",
    "Casual Mode": "休闲模式",
    "Caution: When your score get higher, the game will get harder as well. Be careful to play the game when you have a high score.": "注意：当你的分数越高，游戏也会变得更加困难。 当你获得高分时要小心玩游戏。",
    "Contents (Click the chapters on it to quick-skip!)": "目录（点击其中的章节可以快速跳过！）",
    "Crazy fact: This factor is always 100% before the next update publishes. So you can freely get scholarships every day.^o^": "疯狂的事实：在下一次更新发布之前，这个因子始终是 100%。 这样你每天都可以免费获得奖学金。^o^",
    "Current Evolution": "当前的演变",
    "Every time when you\n                            move or merge blocks, you will gain or lose some score. Your rank depends on your score. The higher difficuty you choose or higher score you have, the harder your score-increasing will be. You can see how high your score and\n                            rank is in the upper-right corner on the page.": "每次移动或合并方块时，您都会获得或失去一些分数。 你的排名取决于你的分数。 你选择的难度越高或者你的分数越高，你的分数增加就越困难。 您可以在页面右上角看到您的分数和\n排名。",
    "Every time when you move or merge\n                            blocks, you will gain or lose some": "每次移动或合并方块时，\n你都会获得或失去一些",
    "Reach Rank-100 in Casual": "在休闲模式中达到 Rank-100",
    "Question block": "问题方块",
    "Question Block": "问题方块",
    "question block": "问题方块",
    "question blocks": "问题方块",
    "Normal Mode": "正常模式",
    "Meet Requirement to see your graduation stats.": "满足要求即可查看您的毕业统计数据。",
    "is limited at 100% without\n                            any boost.": "限制为 100%，\n 没有任何提升。",
    "is in": "在",
    "is a kind of block which look like a negative-number block in the grid. Every": "是一种看起来像网格中的负数方块的方块。 每个",
    "is a kind\n                            of block which look like a positive-number block in the grid. Every": "是一种方块，看起来像网格中的正数方块。 每一个",
    "is a factor affects on scholarship gain. In the first 10\n                            gameplay of a day it is 110%, after 11st gameplay it starts decreasing, and after 101st it's always 0%. The factor refreashes every 86400 seconds(including offline time).": "是影响奖学金获得的一个因素。 在一天的前 10\n 次游戏中，它是 110%，在第 11 次游戏之后，它开始减少，在第 101 次之后，它始终为 0%。 该因子每 86400 秒刷新一次（包括离线时间）。",
    "in the grid will have a chance of mutiplying by 2. This chance is depend on the": "网格中的元素将有几率乘以 2。这个几率取决于",
    "If you can't understand this feature well, the diagram above the text maybe help you.": "如果您不能很好地理解此功能，文本上方的图表可能会对您有所帮助。",
    "If it's your first time to play this game, click the": "如果您是第一次玩此游戏，请点击",
    "Fallen_Cat exhausted all her\n                            stemina and Got a rank of {{formatWhole(calcRank())}} / 1123 in her Final Exam!": "Fallen_Cat 用尽了\n所有的干劲，在期末考试中获得了 {{formatWhole(calcRank())}} / 1123 的排名！",
    "every turn if some": "每个回合，如果一些",
    "or a": "或一个",
    "stamina*": "耐力*",
    "value:": "值:",
    "You have a chance which is higher than upgrade 6 to get a higher-value notebook block.": "升级6以上有几率获得更高价值的笔记本方块。",
    "You have even higher chance to get a higher-value notebook block.": "您更有几率获得更高价值的笔记本方块。",
    "You have higher chance to get a higher-value notebook block.": "您有更高的几率获得更高价值的笔记本方块。",
    "Unlock Undo. Every level add 1 free undo for one gameplay. If you have no undo chance you will lost 90% stamina after undo.": "解锁撤消。 每个级别为一个游戏添加 1 个免费撤消。 如果你没有撤消机会，撤消后你将失去 90% 的耐力。",
    "The": "",
    "Increase maximum stamina": "增加最大耐力",
    "Increase evlove interval": "增加演变间隔",
    "Improve scholarship formula (x^(1/6)->x^(1/4))": "改进奖学金公式(x^(1/6)->x^(1/4))",
    "Get a pre-evloved notebook block after game started.(x2 every level)": "游戏开始后获得预先进化的笔记本方块。（每级x2）",
    "Boost scholarship gain.": "提高奖学金收益。",
    "Boost score gain based on your stamina.": "根据您的耐力提高分数增益。",
    "Best rank increase scholarship gain.": "最好的排名增加奖学金增益。",
    "Add to the base of jump-merging bonus.": "添加到跳跃合并奖励的基础上。",
    ".\n                            When 2": ".\n                            当 2",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Feature: ": "功能: ",
    "The author of this game: ": "本游戏的作者：",
    "Raw score ": "原始分数 ",
    "Rank: ": "排名: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "            ",
    "          ": "",
    "         ": "         ",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = []

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+)iron$/, '$1 白铁'],
    [/^([\d\.,]+)copper$/, '$1 青铜'],
    [/^([\d\.,]+)silver$/, '$1 白银'],
    [/^([\d\.,]+)gold$/, '$1 黄金'],
    [/^([\d\.,]+)ruby$/, '$1 红宝石'],
    [/^Upgrade ([\d\.,]+)$/, '升级 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);